### ISSUE TITLE
CACIB wish to run a sealer node (Andina sealer)

### ISSUE THREAD

**Issue by ghost** [ethereum-pocr/pocrnet#4]
### Company
* Full legal name: Credit Agricole CIB
* Company website: www.ca-cib.com
* Representative contact name: Guénolé de Cadoudal
* Representative contact email: guenole.de-cadoudal@ca-cib.com   

I hereby recognize that our company does not already have a Node in this network

### Sealer Node
* Sealer address: <0xF4358290290E67bDB8ae3457BEEa659302EaE358> (ensure you have the ownership and safekeeping of the private key)
* TBD

### Motivations

CACIB, with SEB, are launching this Proof of Carbon Reduction network as a proposal to establish a public ethereum based network that incentivize virtuous environmental behaviour

**Comment by guenoledc** [comment]
Hello @rghoshfinaxys, I have allowed your this node as sealer

**Comment by guenoledc** [comment]
@rghoshfinaxys I have removed this node because it didn't synchronize and therefore the consensus stale

**Comment by ghost** [comment]
@guenoledc it is synchronizing now, could you add it back again?
I have taken the liberty of proposing it though clique from the cachapa node

**Comment by guenoledc** [comment]
I can't anymore
The bootstrap node is out of the consensus as planned

**Comment by wiktorhejchman** [comment]
@guenoledc @rghoshfinaxys I have placed a vote for it from our sealer already in the network. Should be approved now.
