### ISSUE TITLE
CACIB wish to run a sealer node (Cachapa sealer)

### ISSUE THREAD

**Issue by ghost** [ethereum-pocr/pocrnet#5]
### Company
* Full legal name: Credit Agricole CIB
* Company website: www.ca-cib.com
* Representative contact name: Guénolé de Cadoudal
* Representative contact email: guenole.de-cadoudal@ca-cib.com   

I hereby recognize that our company does not already have a Node in this network

### Sealer Node
* Sealer address: <0x99Cf1eab8c67A76Ea4ce2631352B7A5384E17787> (ensure you have the ownership and safekeeping of the private key)
* TBD

### Motivations

CACIB, with SEB, are launching this Proof of Carbon Reduction network as a proposal to establish a public ethereum based network that incentivize virtuous environmental behaviour

**Comment by guenoledc** [comment]
Now added to the consensus
