### ISSUE TITLE
Skandinaviska Enskilda Banken AB (publ) wish to run a sealer node

### ISSUE THREAD

**Issue by wiktorhejchman** [ethereum-pocr/pocrnet#7]
### Company
* Full legal name: **Skandinaviska Enskilda Banken AB (publ)**   
* Company website: **http://www.sebgroup.com**
* Representative contact name: Sahand Javidi
* Representative contact email: sahand.javidi@seb.se  
* Additional contacts: Johan Hörmark, Anders Hallme, Wiktor Hejchman
* Additional contact emails: johan.hormark@seb.se, anders.hallme@seb.se, wiktor.hejchman@seb.pl

I hereby recognize that our company does not already have a Node in this network

### Sealer Node
* Sealer address: <0xf0f8ccb45672efbd8050571706fb016833b28225>
* Link: TBD

### Motivations

SEB wants to run nodes as a part of the Digital Bond issuance in Project Saturn, where SEB collaborates with CACIB to create a network used for managing the Digital Bond.

**Comment by guenoledc** [comment]
@wiktorhejchman I try to add this node but it didn't start creating blocks. Can you check that you have activated the mining properly ?
I will remove it for now.

**Comment by guenoledc** [comment]
@wiktorhejchman @rghoshfinaxys this sealer is now added 1 vote (over 2 needed)

**Comment by guenoledc** [comment]
@wiktorhejchman @rghoshfinaxys 2 nodes have votes now. You should be sealing properly now
