### ISSUE TITLE
Sintaye4<Company> want to become an auditor

### ISSUE THREAD

**Issue by Sintayew4** [ethereum-pocr/pocrnet#8]
*Fill this form to declare your intention to becoming a node auditor in the production network*

### Company
* Full legal name: ________        
* Company website: _______
* Representative contact name: _______      
* Representative contact email: _______@company.domain    

### Auditor's address
* address: <0x1244...0087> (ensure you have the ownership and safekeeping of the private key)
* Link to your website to prove that your company owns this address

### Motivations

*Explain your reason for joining the network*

**Comment by guenoledc** [comment]
I suppose this was an incorrect request since you have also posted to participate as node sealer. 

Noone can be both

Closing this one
