### ISSUE TITLE
Sintayew4<Company> wish to run a sealer node

### ISSUE THREAD

**Issue by Sintayew4** [ethereum-pocr/pocrnet#9]
*Fill this form to declare your intention to becoming a node operator in the production network*

### Company
* Full legal name: _____sintayew Gashaw___        
* Company website: _____http://www.sintayew4.com__
* Representative contact name: _____sintayew__      
* Representative contact email: _____sintayewgashaw4@gmail.com__@company.domain    

I hereby recognize that our company does not already have a Node in this network

### Sealer Node
* Sealer address: <0x1244...0087> (ensure you have the ownership and safekeeping of the private key)
* Link to your website to prove that your company owns this address

### Motivations

*Explain your reason for joining the network*

**Comment by guenoledc** [comment]
@Sintayew4 

Thanks for the interest but your company name cannot be identified and you have not stated your motivation for joining 

Also I recommend that you first join in Kerleano testnet

Without proper reply this request will be rejected 

Regards
